sudo: false

os:
  - linux

compiler:
  - clang

addons:
  apt:
    sources:
      - deadsnakes
      - ubuntu-toolchain-r-test
    packages:
      - python2.7
      - python2.7-dev
      - python-numpy
      - python-setuptools

notifications:
  email:
    recipients:
      - "discourse-nupic-developers@numenta.org"
    on_success: change
    on_failure: change
  webhooks: "https://webhooks.gitter.im/e/68f77bae61efa5c931f8"

env:
  global:
  - NUPIC=$TRAVIS_BUILD_DIR/nupic
  - NAB=$TRAVIS_BUILD_DIR/NAB
  - "PYTHONPATH=/home/travis/build/numenta/nupic/lib/python2.7/site-packages:/home/travis/.local/lib/python2.7/site-packages:$NUPIC"
  - AWS_ACCESS_KEY_ID=AKIAIGHYSEHV3WFKOWNQ
  - secure: BqIdU+D/Vtt5tydjKc1jxc9tHHu8rK9WIv4VysJD++vRSLERYhaSI3Gy1pjB5rrc/VfdLAqWmC7YdmTwEudyVtl0niUF5Zdtztq777qWK2PCxQBUAAXBqaYKNmHDXaBO0I63oTrfevM6OD7UspHqbBzfJhU9RF9GYSy7mz9cvYM=

virtualenv:
  system_site_packages: true

before_install:
  # - pip install setuptools==20.2.2 --user
  - cd ${TRAVIS_BUILD_DIR}
  - NUPIC_SHA=`cat nupic_sha.txt`
  - echo "Fetching NuPIC source code at SHA ${NUPIC_SHA}"
  - git clone https://github.com/numenta/nupic.git --depth 50
  - (cd nupic && git reset --hard ${NUPIC_SHA})
  # Clone NAB
  - git clone https://github.com/numenta/NAB.git --depth 50


install:
  - echo "Installing nupic.bindings..."
  # Install nupic.bindings at proper version.
  - export NUPIC_BINDINGS_VERSION="$(python get_nupic_bindings_version.py)"
  - "echo Installing nupic.bindings ${NUPIC_BINDINGS_VERSION}"
  - pip install --user https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/releases/nupic.bindings/nupic.bindings-${NUPIC_BINDINGS_VERSION}-cp27-none-linux_x86_64.whl

  - echo "Installing NuPIC..."
  - cd ${NUPIC}
  - python setup.py install --user
  - echo "Installing NAB..."
  - (cd ${NAB} && python setup.py install --user)

  # - "echo PYTHONPATH: $PYTHONPATH"
  # - ls /home/travis/.local/lib/python2.7/site-packages
  # - pip install pytest-xdist --user

  # For regression tests.
  - pip install automatatron --user

script:

  - cd $NUPIC

  # DEBUGGING: Trying to figure out why pytest-xdist is not available when running the swarming tests
  # below.
  # - python -c "from pkg_resources import get_distribution; print repr(get_distribution('pytest-xdist'))"

  # TODO: NuPIC swarming tests are commented out because there is a problem in Travis-CI environment
  # finding the "pytest-xdist" module even though it has clearly been installed.
  # - ./scripts/run_nupic_tests.py -w || exit -1

  # NuPIC example runs
  - . ./ci/travis/script-run-examples.sh

  # Run NAB
  - cd $NAB
  - python run.py -d numenta,numentaTM --detect --score --normalize --skipConfirmation

  - cd $TRAVIS_BUILD_DIR

  # Regressions tests
  - py.test tests/
